### ISSUE TITLE
no marker detection for single fiducial

### ISSUE THREAD

**Issue by jakubaugusty** [andreaskeller96/HoloLens2-IRTracking-Sample#1]
First of all, I would like to congratulate you on a very interesting project for hololens.
However, I have a problem with object detection. The program starts, displays memory usage and number of frames, but it doesn't detect anything from my markers. How can I change the settings to at least detect some noise as in the picture from the article? I need a starting point for further modifications.
![image](https://github.com/andreaskeller96/HoloLens2-IRTracking-Sample/assets/101868974/8e2e1b47-d406-439d-8e9d-5c425f168415)
Alternatively, is it possible to unlock the image from the IR camera, so that you can watch live what is analyzed by the program?
Thank you very much for all your help!

**Comment by andreaskeller96** [comment]
Hey, what does your marker and scene setup look like right now?
I plan to add more debug options as well as some quality of life features to e.g. show the sensor output on request later on, but for now it will be limited to the output you have in the player log as well as the output in visual studio when running with a debugger attached.
Also, make sure that you have research mode enabled on your HoloLens 2.

**Comment by jakubaugusty** [comment]
Hi, research mode is on of course. In the Unity project, I reduced the number of markers to one flat, the rest of the settings are default. In the view of the IR camera, the marker shimmers quite clearly, so there should be no problem with recognition. Am I doing something wrong?
![image](https://github.com/andreaskeller96/HoloLens2-IRTracking-Sample/assets/101868974/eb11ac79-ce4c-4e6b-a6af-ebf71d6edd57)

![image](https://github.com/andreaskeller96/HoloLens2-IRTracking-Sample/assets/101868974/e01dd55f-6c89-4c20-8abe-cdabb00685d6)


![20230718_224111_HoloLens](https://github.com/andreaskeller96/HoloLens2-IRTracking-Sample/assets/101868974/f25b89bf-42f0-400c-a0f4-054bb90319f8)

**Comment by andreaskeller96** [comment]
Ah okay, you’re gonna need a minimum of 3 markers to be able to track a marker array. Stability will be better with 4 or more.

**Comment by jakubaugusty** [comment]
Thanks for the instant reply! Where can I change the settings regarding the number of required markers? I mainly want the program to detect markers without tracking them in 3D space.

**Comment by andreaskeller96** [comment]
The library currently does not support this, you would need to adjust the library itself and it would create lots of false positives. I highly suggest using 3 or more markers.
If you want to adjust the library yourself to expose all detections and try to find a single marker, you can clone this repo and make adjustments: https://github.com/andreaskeller96/HoloLens2-IRTracking
