### ISSUE TITLE
Kalman filter

### ISSUE THREAD

**Issue by Nacy09** [andreaskeller96/HoloLens2-IRTracking-Sample#5]
Hello，
May I ask if the project uses a Kalman filter? In which file can I find relevant information about Kalman filters?

**Comment by andreaskeller96** [comment]
Yes, the project uses both a lowpass and a kalman filter within the library. The relevant file is https://github.com/andreaskeller96/HoloLens2-IRTracking/blob/main/IRKalmanFilter.h

Sorry for the late response, I must have overlooked this.
