### ISSUE TITLE
Help Troubleshooting - Solution: improved tape quality

### ISSUE THREAD

**Issue by joseerosset** [andreaskeller96/HoloLens2-IRTracking-Sample#6]
Hello andreaskeller96! Thank you for sharing your project! I'm hoping you can help me with some troubleshooting...

I'm using:
Visual Studio 2022
Unity 2022.3.16f1

I've tried Unity 2021.3.18f1 to the same effect.
I'm running Visual Studio in ADMIN mode.

I printed the model you supplied and am using flat IR tape. The single change I made to the sample was to change the radius of the spheres to 0. I've also modified the manifest according to @petergu684 's HoloLens2-ResearchMode-Unity - but alas not luck!

I would be very grateful for any help you can provide :)
![image0](https://github.com/user-attachments/assets/f1a83563-f52e-4aae-8bb4-8205fd7d2ba9)
[BuildOutput_HL2IRToolTrackingSample.txt](https://github.com/user-attachments/files/16367397/BuildOutput_HL2IRToolTrackingSample.txt)

**Comment by andreaskeller96** [comment]
From the log you provided, it all looks correct. Only thing i could possibly see happening is that the tape is not reflective enough, but that is a long shot. Try placing the marker such that it faces the headset head on, at a distance of about arms length and see if detection works.
Other than that, all I can think of is double checking that the sample scene is setup correctly (you can even run it 100% normal, so with radius 6.5, it will only show tha tool 6.5mm offset from the actual position in that case).

**Comment by joseerosset** [comment]
Thank you for your reply! I rebuilt and this time made no modifications. I included the notes from releasing it in visual studio and debugging it. 

Could the errors below be the source of the problem?
[Debug_Notes_07_29.txt](https://github.com/user-attachments/files/16419236/Debug_Notes_07_29.txt)
[ReleaseNotes_07_29.txt](https://github.com/user-attachments/files/16419239/ReleaseNotes_07_29.txt)


[XR] [4888] [14:06:49.187][Info   ] Stage 1 Missing Entry Points: (1)
[XR] [4888] [14:06:49.190][Info   ]   xrInitializeLoaderKHR
[XR] [4888] [14:06:49.191][Info   ] 
[XR] [4888] [14:06:49.191][Info   ] Stage 2 Missing Entry Points: (5)
[XR] [4888] [14:06:49.193][Info   ]   xrGetVisibilityMaskKHR
[XR] [4888] [14:06:49.193][Info   ]   xrGetD3D12GraphicsRequirementsKHR
[XR] [4888] [14:06:49.194][Info   ]   xrCreateFoveationProfileFB
[XR] [4888] [14:06:49.194][Info   ]   xrDestroyFoveationProfileFB
[XR] [4888] [14:06:49.195][Info   ]   xrUpdateSwapchainFB

[XR] [4888] [14:06:49.203][Info   ] Requested feature extensions not supported by runtime: (3)
[XR] [4888] [14:06:49.203][Info   ]   XR_MSFT_spatial_anchor_export_preview: Feature="Mixed Reality Features": Version=1.5.1, Company="Microsoft"
[XR] [4888] [14:06:49.204][Info   ]   XR_MSFT_controller_model: Feature="Motion Controller Model": Version=1.5.1, Company="Microsoft"
[XR] [4888] [14:06:49.204][Info   ]   XR_FB_render_model: Feature="Motion Controller Model": Version=1.5.1, Company="Microsoft"

**Comment by andreaskeller96** [comment]
According to your output, it seems like setting the reference coordinate system is failing somehow. That is what is causing the "Trans to world is null" error.
it is being set here: https://github.com/andreaskeller96/HoloLens2-IRTracking-Sample/blob/6ce34568e662c5f1e453feb3b82d0d988fab5a26/Assets/HoloLensIRTracking/Scripts/IRToolTrack/IRToolTracking.cs#L98
and is dependent on the unity version, so maybe something has changed there on the unity side.

I dont have a headset available currently so i cannot test it myself unfortunately. Another thing you could try is updating the HoloLens operating system to the newest version, maybe you are on an old version or there is an issue there.

**Comment by joseerosset** [comment]
Your remark on the tape not being reflective enough stuck with me. I upgraded to ifm E21015 Reflective tape and it's now working as expected!

Thank you for your help :)

**Comment by andreaskeller96** [comment]
Great to hear! Thanks for posting the fix here too :)
