### ISSUE TITLE
How I can use it with Mixed Reality Capture? My app crashed when I turn on live preview or capture image

### ISSUE THREAD

**Issue by catnull-dev** [andreaskeller96/HoloLens2-IRTracking-Sample#7]

**Comment by andreaskeller96** [comment]
Hey,
There’s nothing preventing it from working in the library generally. However, with some HoloLens OS versions there was a bug that you couldn’t access the rgb camera and other sensors simultaneously. This should be fixed in the newest OS though so an operating system update should fix it.

**Comment by catnull-dev** [comment]
Thanks for help!
