### ISSUE TITLE
Camera inaccessible

### ISSUE THREAD

**Issue by longlong383** [andreaskeller96/HoloLens2-IRTracking-Sample#9]
Hi Andrea,

Hope this finds you well! I'm having some trouble with the project accessing the camera on my hololens. When I configure and deploy the solution, it does so without a compilation issue. However, I believe there normally should be a prompt from the deployed app asking to access the camera when you open the app for the first time. The IR tracking has not worked for me, and I believe the issue has something to do with the project accessing the camera, and I was wondering if you had any idea why this could be?

Unity Editor Version: 2022.3.45f1

Thanks

**Comment by andreaskeller96** [comment]
Hey longlong,
my best guess without any more information is that the headset is not set to use research mode.
If thats not it, for more of a diagnosis youd need to check the visual studio output when running with a debugger attached

**Comment by longlong383** [comment]
I was able to solve the issue with a clone from a different person. I honestly am not sure what the issue was, as the hololens was on research mode.
